#The health index the first try?
#I have no idea what is going on and how to caculate it but lets try sommething first 

#try to using the scale method to do it?
#make it try

#load the package

rm(list = ls())
dev.off()
#make sure clean the environment

#create a new file for all the generated by the graphy
dir.create("Data")

#Step one Lode the all package that necessary. 
library (lubridate)    
library (cansim)       
library (OECD)        
library (WDI)          
library (fredr)        
library (tsbox)
library (RColorBrewer)
library(wesanderson)
library(writexl)
library(dplyr)


#let's set the start year

#things we have to include

###########
#0.0 try to build a functional one first

###########
#The data this project need to include
###########
#cost of living, 
#affordability 
#purchasing power sub-indices,
#indicators on household and/or individual incomes
#indicators measuring the accessibility of
 #transportation
 #hospitals,
  #educational, 
 #recreational 
 #cultural facilities, 
#pollution rates- the extreme weather? 
  #wild fire
  

#crime rates - its got the index 


########
#the data this project will using?
#affordability - disposable income



##########
#The data import and clearing
##########

#start with the unemployment rate

#1 The labor data
#1.1 Labor force characteristics, monthly, seasonally adjusted and trend-cycle
#unemployment seasonally adjusted (2000-2022)
#https://www150.statcan.gc.ca/n1/daily-quotidien/220909/dq220909a-eng.htm?indid=3587-2&indgeo=0
#the report wrote by the statistics Canada
#get the data form statistic Canada
unemployment_rate_raw <- "v2062815" #the series number for the statstic canada 
unemployment.st <- get_cansim_vector(unemployment_rate_raw, start_time = "2000-01-01")
unemployment_rate_year.st <- year(unemployment.st$REF_DATE[1])
unemployment_rate_month.st <- month(unemployment.st$REF_DATE[1])

#transfer data to the time series time
c(unemployment_rate_year.st, unemployment_rate_month.st)
unemployment_rate.ts<- ts(unemployment.st$VALUE, start = c(unemployment_rate_year.st, unemployment_rate_month.st), freq = 12)
#now its time series data!

plot(unemployment_rate.ts, col= "#003B6F",lwd=2.4)
#draw the data, color and the wide of the line
legend('topleft', lty=1,lwd=2.4, legend= c('unemployment rate'), col = c("#003B6F")) #Tardis blue

#let's try using teh dplyr and lubridate for the time series normalization
unemployment_rate.ts <- unemployment_rate.ts %>% mutate(
  normalized_unemployment_rate_norm <- (value -min(value))/(max(value) - min(value))
)

#the best part of this is that I can reuse it over and over again....


##### affortablility?
  #possible idea
    #CPI
    #house price to income ratio
    #rent to income ration
    #living wage calculations
    #real wage
    #debt_to_income ratios


##############
#affordability sub index
##############
#The affordability index 0.1
  #short verson using
    #. Discretionary Income


######CPI
#https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1810000501
#v41693271
#the things is the CPI is base on the 2002 

CPI_raw <- "v41693271" #the series number for the statstic canada 
CPI.st <- get_cansim_vector(CPI_raw, start_time = "2000-01-01", end_time = "2023-01-01")
CPI_year.st <- year(CPI.st$REF_DATE[1])
CPI_month.st <- month(CPI.st$REF_DATE[1])

#transfer data to the time series time
c(CPI_year.st, CPI_month.st)
CPI.ts<- ts(CPI.st$VALUE, start = c(CPI_year.st, CPI_month.st), freq = 1)
#now its time series data!
#######
#### transfer the CPI into the adjusting factor
CPI_adjust_factor <- 100/CPI.ts
####### 


######Adjusted household disposable income
#https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=3610058801
HDI_raw <- "v1059426366" #the series number for the statstic canada 
HDI.st <- get_cansim_vector(HDI_raw, start_time = "2000-01-01", end_time = "2023-01-01")
HDI_year.st <- year(HDI.st$REF_DATE[1])
HDI_month.st <- month(HDI.st$REF_DATE[1])

#transfer data to the time series time
c(HDI_year.st, HDI_month.st)
HDI.ts<- ts(HDI.st$VALUE, start = c(HDI_year.st, HDI_month.st), freq = 1)
#now its time series data!
#adjust the HDI now
adjust_HDI_ts <- HDI.ts * CPI_adjust_factor

plot(HDI.ts)
lines(adjust_HDI_ts)

plot(adjusted_HDI.ts, col= "#003B6F",lwd=2.4)
#draw the data, color and the wide of the line
legend('topleft', lty=1,lwd=2.4, legend= c('adjusted_HDI'), col = c("#003B6F")) #Tardis blue

#transfer it into the year over year growth rate
adjusted_HDI.yoy <- diff(log(adjusted_HDI.ts), 1)

plot(adjusted_HDI.yoy, type = "l",col= "#003B6F",lwd=2.4, 
     main = 'Canadian HDI change 2001-2023', ylab = 'the percantage change', xlab = 'time')
abline(h = 0)
rect(xleft= 2015, ybottom = -4, xright= 2023, ytop=0, col= "#003B6F23")
#p/l/b/o/s/h/n
#Points plot (default)/Line plot/Both (points and line)/Both (overplotted)/Both (overplotted)/Histogram-like plot/No plotting

######
# Household final consumption expenditure (HFCE)
#v116885921
HFCE_raw <- "v116885921" #the series number for the statstic canada 
HFCE.st <- get_cansim_vector(HFCE_raw, start_time = "2000-01-01", end_time = "2023-01-01")
HFCE_year.st <- year(HFCE.st$REF_DATE[1])
HFCE_month.st <- month(HFCE.st$REF_DATE[1])

#transfer data to the time series time
c(HFCE_year.st, HFCE_month.st)
HFCE.ts<- ts(HFCE.st$VALUE, start = c(HFCE_year.st,HFCE_month.st), freq = 1)
#now its time series data!

#adjust_HFCE.ts
adjust_HFCE.ts <-HFCE.ts * CPI_adjust_factor

####
#Disposable Income Surplus=Real HDI−Real HFCE
disposable_income_surplus <- adjust_HDI_ts  - adjust_HFCE.ts 
#plot(disposable_income_surplus )
#####
#what is going on here? 
disposable_income_surplus.yoy <- diff(log(disposable_income_surplus),1)

#its seem wield? 
#let transfer it anyway?

library(dplyr)

# Convert the time series to a data frame
disposable_income_surplus_df <- data.frame(value = as.numeric(disposable_income_surplus.yoy))

# Scale the values using dplyr
disposable_income_surplus_scale <- disposable_income_surplus_df%>%
  mutate(scaled_value = (value - min(value, na.rm = TRUE)) / 
           (max(value, na.rm = TRUE) - min(value, na.rm = TRUE)))

plot(disposable_income_surplus_scale$scaled_value, type = "l")
