#The health index the first try?
#I have no idea what is going on and how to caculate it but lets try sommething first 

#try to using the scale method to do it?
#make it try

#load the package

rm(list = ls())
dev.off()
#make sure clean the environment

#create a new file for all the generated by the graphy
dir.create("Data")

#Step one Lode the all package that necessary. 
library (lubridate)    
library (cansim)       
library (OECD)        
library (WDI)          
library (fredr)        
library (tsbox)
library (RColorBrewer)
library(wesanderson)
library(writexl)
library(dplyr)


#let's set the start year

#things we have to include

###########
#0.0 try to build a functional one first

###########
#The data this project need to include
###########
#cost of living, 
#affordability 
#purchasing power sub-indices,
#indicators on household and/or individual incomes
#indicators measuring the accessibility of
 #transportation
 #hospitals,
  #educational, 
 #recreational 
 #cultural facilities, 
#pollution rates- the extreme weather? 
  #wild fire
  

#crime rates - its got the index 


########
#the data this project will using?
#affordability - disposable income



##########
#The data import and clearing
##########

#start with the unemployment rate

#1 The labor data
#1.1 Labor force characteristics, monthly, seasonally adjusted and trend-cycle
#unemployment seasonally adjusted (2000-2022)
#https://www150.statcan.gc.ca/n1/daily-quotidien/220909/dq220909a-eng.htm?indid=3587-2&indgeo=0
#the report wrote by the statistics Canada
#get the data form statistic Canada
unemployment_rate_raw <- "v2062815" #the series number for the statstic canada 
unemployment.st <- get_cansim_vector(unemployment_rate_raw, start_time = "2000-01-01")
unemployment_rate_year.st <- year(unemployment.st$REF_DATE[1])
unemployment_rate_month.st <- month(unemployment.st$REF_DATE[1])

#transfer data to the time series time
c(unemployment_rate_year.st, unemployment_rate_month.st)
unemployment_rate.ts<- ts(unemployment.st$VALUE, start = c(unemployment_rate_year.st, unemployment_rate_month.st), freq = 12)
#now its time series data!

plot(unemployment_rate.ts, col= "#003B6F",lwd=2.4)
#draw the data, color and the wide of the line
legend('topleft', lty=1,lwd=2.4, legend= c('unemployment rate'), col = c("#003B6F")) #Tardis blue

#let's try using teh dplyr and lubridate for the time series normalization
unemployment_rate.ts <- unemployment_rate.ts %>% mutate(
  normalized_unemployment_rate_norm <- (value -min(value))/(max(value) - min(value))
)

#the best part of this is that I can reuse it over and over again....


##### affortablility?
  #possible idea
    #CPI
    #house price to income ratio
    #rent to income ration
    #living wage calculations
    #real wage
    #debt_to_income ratios


##############
#affordability sub index
##############
#The affordability index 0.1
  #short verson using
    #. Discretionary Income



######Adjusted household disposable income
#https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=3610058801
adjusted_HDI_raw <- "v1059426366" #the series number for the statstic canada 
adjusted_HDI.st <- get_cansim_vector(adjusted_HDI_raw, start_time = "2000-01-01")
adjusted_HDI_year.st <- year(adjusted_HDI.st$REF_DATE[1])
adjusted_HDI_month.st <- month(adjusted_HDI.st$REF_DATE[1])

#transfer data to the time series time
c(adjusted_HDI_year.st, adjusted_HDI_month.st)
adjusted_HDI.ts<- ts(adjusted_HDI.st$VALUE, start = c(adjusted_HDI_year.st, adjusted_HDI_month.st), freq = 1)
#now its time series data!

plot(adjusted_HDI.ts, col= "#003B6F",lwd=2.4)
#draw the data, color and the wide of the line
legend('topleft', lty=1,lwd=2.4, legend= c('adjusted_HDI'), col = c("#003B6F")) #Tardis blue

###### CPI
#https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1810000501
#v41693271

CPI_raw <- "v41693271" #the series number for the statstic canada 
CPI.st <- get_cansim_vector(CPI_raw, start_time = "2000-01-01")
CPI_year.st <- year(CPI.st$REF_DATE[1])
CPI_month.st <- month(CPI.st$REF_DATE[1])

#transfer data to the time series time
c(CPI_year.st, CPI_month.st)
CPI.ts<- ts(CPI.st$VALUE, start = c(CPI_year.st, CPI_month.st), freq = 1)
#now its time series data!

plot(CPI.ts, col= "#003B6F",lwd=2.4)
#draw the data, color and the wide of the line
legend('topleft', lty=1,lwd=2.4, legend= c('adjusted_HDI'), col = c("#003B6F")) #Tardis blue





######
# Household final consumption expenditure (HFCE)
######




