#The health index the first try?
#I have no idea what is going on and how to caculate it but lets try sommething first 

#try to using the scale method to do it?
#make it try

#load the package

rm(list = ls())

#make sure clean the environment

#create a new file for all the generated by the graphy
dir.create("Data")

#Step one Lode the all package that necessary. 
library (lubridate)    
library (cansim)       
library (OECD)        
library (WDI)          
library (fredr)        
library (tsbox)
library (RColorBrewer)
library(wesanderson)
library(writexl)
library(dplyr)
library(dplyr)



#let's set the start year

#things we have to include

###########
#0.0 try to build a functional one first

###########
#The data this project need to include
###########
#cost of living, 
#affordability 
#purchasing power sub-indices,
#indicators on household and/or individual incomes
#indicators measuring the accessibility of
 #transportation
 #hospitals,
  #educational, 
 #recreational 
 #cultural facilities, 
#pollution rates- the extreme weather? 
  #wild fire
  

#crime rates - its got the index 


########
#the data this project will using?
#affordability - disposable income



##########
#The data import and clearing
##########

#start with the unemployment rate

#1 The labor data
#1.1 Labor force characteristics, monthly, seasonally adjusted and trend-cycle
#unemployment seasonally adjusted (2000-2022)
#https://www150.statcan.gc.ca/n1/daily-quotidien/220909/dq220909a-eng.htm?indid=3587-2&indgeo=0
#the report wrote by the statistics Canada
#get the data form statistic Canada
unemployment_rate_raw <- "v2062815" #the series number for the statstic canada 
unemployment.st <- get_cansim_vector(unemployment_rate_raw, start_time = "2000-01-01")
unemployment_rate_year.st <- year(unemployment.st$REF_DATE[1])
unemployment_rate_month.st <- month(unemployment.st$REF_DATE[1])

#transfer data to the time series time
c(unemployment_rate_year.st, unemployment_rate_month.st)
unemployment_rate.ts<- ts(unemployment.st$VALUE, start = c(unemployment_rate_year.st, unemployment_rate_month.st), freq = 12)
#now its time series data!

plot(unemployment_rate.ts, col= "#003B6F",lwd=2.4)
#draw the data, color and the wide of the line
legend('topleft', lty=1,lwd=2.4, legend= c('unemployment rate'), col = c("#003B6F")) #Tardis blue

#let's try using teh dplyr and lubridate for the time series normalization
unemployment_rate.ts <- unemployment_rate.ts %>% mutate(
  normalized_unemployment_rate_norm <- (value -min(value))/(max(value) - min(value))
)

#the best part of this is that I can reuse it over and over again....


##### affortablility?
  #possible idea
    #CPI
    #house price to income ratio
    #rent to income ration
    #living wage calculations
    #real wage
    #debt_to_income ratios


##############
#affordability sub index
##############
#The affordability index 0.1
  #short verson using
    #. Discretionary Income

rm(list = ls())

######CPI
#https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1810000501
#v41693271
#the things is the CPI is base on the 2002 

CPI_raw <- "v41693271" #the series number for the statstic canada 
CPI.st <- get_cansim_vector(CPI_raw, start_time = "2000-01-01", end_time = "2023-01-01")
CPI_year.st <- year(CPI.st$REF_DATE[1])
CPI_month.st <- month(CPI.st$REF_DATE[1])

#transfer data to the time series time
c(CPI_year.st, CPI_month.st)
CPI.ts<- ts(CPI.st$VALUE, start = c(CPI_year.st, CPI_month.st), freq = 1)
#now its time series data!
#######
#### transfer the CPI into the adjusting factor
CPI_adjust_factor <- 100/CPI.ts
####### 


######household disposable income
#https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=3610058801
HDI_raw <- "v1059426366" #the series number for the statstic canada 
HDI.st <- get_cansim_vector(HDI_raw, start_time = "2000-01-01", end_time = "2023-01-01")
HDI_year.st <- year(HDI.st$REF_DATE[1])
HDI_month.st <- month(HDI.st$REF_DATE[1])

#transfer data to the time series time
c(HDI_year.st, HDI_month.st)
HDI.ts<- ts(HDI.st$VALUE, start = c(HDI_year.st, HDI_month.st), freq = 1)
#now its time series data!
#adjust the HDI now
adjust_HDI_ts <- HDI.ts * CPI_adjust_factor

plot(HDI.ts)
lines(adjust_HDI_ts)

plot(adjusted_HDI.ts, col= "#003B6F",lwd=2.4)
#draw the data, color and the wide of the line
legend('topleft', lty=1,lwd=2.4, legend= c('adjusted_HDI'), col = c("#003B6F")) #Tardis blue

#transfer it into the year over year growth rate
adjusted_HDI.yoy <- diff(log(adjusted_HDI.ts), 1)

plot(adjusted_HDI.yoy, type = "l",col= "#003B6F",lwd=2.4, 
     main = 'Canadian HDI change 2001-2023', ylab = 'the percantage change', xlab = 'time')
abline(h = 0)
rect(xleft= 2015, ybottom = -4, xright= 2023, ytop=0, col= "#003B6F23")
#p/l/b/o/s/h/n
#Points plot (default)/Line plot/Both (points and line)/Both (overplotted)/Both (overplotted)/Histogram-like plot/No plotting

######
# Household final consumption expenditure (HFCE)
#v116885921
HFCE_raw <- "v116885921" #the series number for the statstic canada 
HFCE.st <- get_cansim_vector(HFCE_raw, start_time = "2000-01-01", end_time = "2023-01-01")
HFCE_year.st <- year(HFCE.st$REF_DATE[1])
HFCE_month.st <- month(HFCE.st$REF_DATE[1])

#transfer data to the time series time
c(HFCE_year.st, HFCE_month.st)
HFCE.ts<- ts(HFCE.st$VALUE, start = c(HFCE_year.st,HFCE_month.st), freq = 1)
#now its time series data!

#adjust_HFCE.ts
adjust_HFCE.ts <-HFCE.ts * CPI_adjust_factor

####
#Disposable Income Surplus=Real HDI−Real HFCE
disposable_income_surplus <- adjust_HDI_ts  - adjust_HFCE.ts 
#plot(disposable_income_surplus )
#####
#what is going on here? 
disposable_income_ssurplus.yoy <- diff(log(disposable_income_surplus),1)


# Define the years as a vector
years <- 2000:2023

# Define base year
base_year <- 2002

# Ensure base_year and years are comparable and correctly typed
base_year <- as.integer(base_year)
years <- as.integer(years)

# Finding the index of the base year
base_year_index <- which(years == base_year)

# Get the disposable income surplus for the base year
base_year_income_surplus <- disposable_income_surplus[base_year_index]

# Scale the disposable income surplus data to set the base year as 100%
scaled_income_surplus <- (disposable_income_surplus / base_year_income_surplus) * 100

# Create a data frame for better visualization
scaled_income_surplus_data <- data.frame(Year = years, ScaledIncomeSurplus = scaled_income_surplus)

# Print the scaled data
print(scaled_income_surplus_data)

# Optional: Plotting the scaled disposable income surplus
if("ggplot2" %in% rownames(installed.packages()) == FALSE) {
  install.packages("ggplot2")
}
library(ggplot2)

ggplot(scaled_income_surplus_data, aes(x = Year, y = ScaledIncomeSurplus)) +
  geom_line(color = "blue", size = 1) +
  geom_hline(yintercept = 100, linetype="dashed", color = "red") +
  labs(title = "Scaled Disposable Income Surplus Relative to 2002",
       x = "Year",
       y = "Income Surplus as % of 2002 Value") +
  theme_minimal()


######## 
########
#new idea, money spend on food shelter and energy percentage of 
#Household final consumption expenditure

rm(list = ls())

######
# Household final consumption expenditure (HFCE)
#https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3610010701
#v116885921
HFCE_raw <- "v116885921" #the series number for the statstic canada 
HFCE.st <- get_cansim_vector(HFCE_raw, start_time = "2000-01-01", end_time = "2023-01-01")
HFCE_year.st <- year(HFCE.st$REF_DATE[1])
HFCE_month.st <- month(HFCE.st$REF_DATE[1])

#transfer data to the time series time
c(HFCE_year.st, HFCE_month.st)
HFCE.ts<- ts(HFCE.st$VALUE, start = c(HFCE_year.st,HFCE_month.st), freq = 1)
#now its time series data!

##########
#v61988959 food
#v61988967 Housing, water, electricity, gas and other fuels 
#v61988968 Paid rental fees for housing 
#v61988972 Electricity, gas and other fuels
rm(list = ls())
##########
food_spending_raw <- "v61988959" #the series number for the statstic canada 
food_spending.st <- get_cansim_vector(food_spending_raw, start_time = "2000-01-01", end_time = "2023-01-01")
food_spending_year.st <- year(food_spending.st$REF_DATE[1])
food_spending_month.st <- month(food_spending.st$REF_DATE[1])

#transfer data to the time series time
c(food_spending_year.st, food_spending_month.st)
food_spending.ts<- ts(food_spending.st$VALUE, start = c(food_spending_year.st, food_spending_month.st), freq = 4)
#now its time series data!

######### housing and energy
housing_and_energy_raw <- "v61988967" #the series number for the statstic canada 
housing_and_energy.st <- get_cansim_vector(housing_and_energy_raw, start_time = "2000-01-01", end_time = "2023-01-01")
housing_and_energy_year.st <- year(housing_and_energy.st$REF_DATE[1])
housing_and_energy_month.st <- month(housing_and_energy.st$REF_DATE[1])

#transfer data to the time series time
c(housing_and_energy_year.st, housing_and_energy_month.st)
housing_and_energy.ts<- ts(housing_and_energy.st$VALUE, start = c(housing_and_energy_year.st, housing_and_energy_month.st), freq = 4)
#now its time series data!

######### rental_Payment
rental_payment_raw <- "v61988968" #the series number for the statstic canada 
rental_payment.st <- get_cansim_vector(rental_payment_raw, start_time = "2000-01-01", end_time = "2023-01-01")
rental_payment_year.st <- year(rental_payment.st$REF_DATE[1])
rental_payment_month.st <- month(rental_payment.st$REF_DATE[1])

#transfer data to the time series time
c(rental_payment_year.st, rental_payment_month.st)
rental_payment.ts<- ts(rental_payment.st$VALUE, start = c(rental_payment_year.st, rental_payment_month.st), freq = 4)
#now its time series data!

######enegy
#v61988972
enegy_raw <- "v61988972" #the series number for the statstic canada 
enegy.st <- get_cansim_vector(enegy_raw, start_time = "2000-01-01", end_time = "2023-01-01")
enegy_year.st <- year(enegy.st$REF_DATE[1])
enegy_month.st <- month(enegy.st$REF_DATE[1])

#transfer data to the time series time
c(enegy_year.st, enegy_month.st)
enegy.ts<- ts(enegy.st$VALUE, start = c(enegy_year.st, enegy_month.st), freq = 4)
#now its time series data!

###### 
#Water supply and sanitation services 
#v61988971
water_cost_raw <- "v61988971" #the series number for the statstic canada 
water_cost.st <- get_cansim_vector(water_cost_raw, start_time = "2000-01-01", end_time = "2023-01-01")
water_cost_year.st <- year(water_cost.st$REF_DATE[1])
water_cost_month.st <- month(water_cost.st$REF_DATE[1])

#transfer data to the time series time
c(water_cost_year.st, water_cost_month.st)
water_cost.ts<- ts(water_cost.st$VALUE, start = c(water_cost_year.st, water_cost_month.st), freq = 4)
#######

###### Imputed rental fees for housing 
#v61988969
Imputed_rental_fees_raw <- "v61988969" #the series number for the statstic canada 
Imputed_rental_fees.st <- get_cansim_vector(Imputed_rental_fees_raw, start_time = "2000-01-01", end_time = "2023-01-01")
Imputed_rental_fees_year.st <- year(Imputed_rental_fees.st $REF_DATE[1])
Imputed_rental_fees_month.st <- month(Imputed_rental_fees.st $REF_DATE[1])

#transfer data to the time series time
c(Imputed_rental_fees_year.st, Imputed_rental_fees_month.st)
Imputed_rental_fees.ts<- ts(Imputed_rental_fees.st$VALUE, start = c(Imputed_rental_fees_year.st, Imputed_rental_fees_month.st), freq = 4)
######
The_housing_cost <-  water_cost.ts + enegy.ts + rental_payment.ts + Imputed_rental_fees.ts

plot((diff(log(The_housing_cost),4))*100)


####### 
#v61989012 Household final consumption expenditure 

final_consumption_raw <- "v61989012" #the series number for the statstic canada 
final_consumption.st <- get_cansim_vector(final_consumption_raw, start_time = "2000-01-01", end_time = "2023-01-01")
final_consumption_year.st <- year(final_consumption.st$REF_DATE[1])
final_consumption_month.st <- month(final_consumption.st$REF_DATE[1])

#transfer data to the time series time
c(final_consumption_year.st, final_consumption_month.st)
final_consumption.ts<- ts(final_consumption.st$VALUE, start = c(final_consumption_year.st, final_consumption_month.st), freq = 4)
#now its time series data!

#the percentage of the necessity of the spending in family. 

the_percentage <- ((food_spending.ts +water_cost.ts + enegy.ts + rental_payment.ts + Imputed_rental_fees.ts)/final_consumption.ts)*100
plot(the_percentage)


##### the affortability index
the_percentage.df <- data.frame(
  Time = time(the_percentage),    # Create a time column from the time series index
  Value = as.numeric(the_percentage)  # Extract values from the time series
)

# Apply mutate to scale the 'Value' within the data frame
the_percentage.df <- the_percentage.df %>%
  mutate(Scaled_Value = (Value - min(Value)) / (max(Value) - min(Value)))

affortability_index <- 1 - the_percentage.df$Scaled_Value

plot(affortability_index, type = "l")

summary(affortability_index)
#####




